### ISSUE TITLE
is it possible to extend variant?

### ISSUE THREAD

**Issue by seeden** [smooth-code/xstyled#100]
in styled-system you can do extend variant inside your template

```js
{
  heading: {
    fontSize: 1,
    color: 'heading',
    marginBottom: 4,
  },
  h1: {
    variant: 'heading',
    font-size: 3;
  },
}
```

Is it possible something similar with xstyled? 
I understand that you need to use css.

```js
{
  heading: css`
    font-size: 1;
    color: heading;
    margin-bottom: 4;
  `,
  h1: css`
    variant: heading;
    or
    ${variant('heading')}
    font-size: 3;
  },
}
```

It would be very nice to have this feature.

**Comment by gregberge** [comment]
For now it is not possible, but you could easily create your own helper to do it.
