### ISSUE TITLE
Raw colors not being updated

### ISSUE THREAD

**Issue by javialon26** [smooth-code/xstyled#102]
## 🐛 Bug Report

I'm using the color mode and some utilities from polished, for example [rgba](https://polished.js.org/docs/#rgb). This helper needs a raw color as an argument, not a custom CSS property. When the color mode is active the colors are replaced with CSS custom properties.

I found the __rawColors object in the theme but when I change the mode this object always has the original colors.

## To Reproduce

Activate the color mode and try to access to raw colors through the props.theme.__rawColors and change the color mode.

## Expected behavior

Maybe we need a way to access current raw colors, can be a new object in the theme, also can be a new param in the th getter.

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/react-example-k7fbm

## Run `npx envinfo --system --binaries --npmPackages @xstyled/system,@xstyled/styled-components,styled-components --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
 - CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
 - Memory: 7.66 GB / 15.53 GB
 - Container: Yes
 - Shell: 5.4.2 - /usr/bin/zsh
## Binaries:
 - Node: 12.14.1 - /usr/local/bin/node
 - Yarn: 1.21.1 - /usr/bin/yarn
 - npm: 6.13.7 - /usr/local/bin/npm
## npmPackages:
 - @xstyled/styled-components: ^1.16.0 => 1.16.0 
 - @xstyled/system: ^1.16.0 => 1.16.0 
 - styled-components: ^5.0.1 => 5.0.1 
```

**Comment by javialon26** [comment]
Related with https://github.com/smooth-code/xstyled/issues/78. I think deactivate custom css properties is a buggy workaround because of the flashing problem in SSR.

**Comment by gregberge** [comment]
The solution is to compute every colors statically in the theme. You can't transform colors dynamically using css properties. It is a CSS limitation. We should mention it in the documentation.
