### ISSUE TITLE
Prop-types documentation page on the website needs fixing

### ISSUE THREAD

**Issue by ramyma** [smooth-code/xstyled#107]
## 🐛 Bug Report

Prop-types [documentation page](https://xstyled.dev/docs/prop-types/#how-to-get-prop-types) shows `getUtilityPropTypes`` instead of `getSystemPropTypes` as per https://github.com/smooth-code/xstyled/blob/master/packages/prop-types/src/index.js#L3
## To Reproduce

Check https://github.com/smooth-code/xstyled/blob/master/packages/prop-types/src/index.js#L3
## Expected behavior

`getUtilityPropTypes` should be referenced

## Link to repl or repo (highly encouraged)

https://github.com/smooth-code/xstyled/pull/106

**Comment by gregberge** [comment]
Fixed in #106
