### ISSUE TITLE
@xstyled/util, lodash, typescript

### ISSUE THREAD

**Issue by cyrilchapon** [smooth-code/xstyled#109]
## 💬 Questions and Help

Hey :) I'm preparing a massive contribution on DefinatelyTyped for typing xstyled and smooth-ui

(I might open an issue and PR for this to track progress.)

But first things first; I'm starting with @xstyled/util.

Question: _Why on earth partially reimplementing some - already coded, battletested, well typed - lodashish functions instead of just installing lodash ?_

The question might seem stupid; (I know, byte size, dependencies and stuff); but this is 2020, lodash have deep imports and we have tree shaking.. 😄 

Mind if I PR a drop-in replacement for this ?

**Comment by gregberge** [comment]
Hello @cyrilchapon, xstyled is heavily optimized.

```
@xstyled/system x 781,809 ops/sec ±0.56% (85 runs sampled)
styled-system x 624,517 ops/sec ±0.65% (90 runs sampled)
Fastest is @xstyled/system
```

Every functions are carefully optimized, so I prefer to keep control on everything. I don't want to use lodash. Lodash is designed to handle lots of usecases not to be performant.
