### ISSUE TITLE
Override styled.xxx with styled.xxxBox?

### ISSUE THREAD

**Issue by good-idea** [smooth-code/xstyled#111]
## 🚀 Feature Proposal

Override styled-components base tags with the "Box" tags, making the theme utilities available.

## Motivation

When using something like `styled.div`, I would expect to be able to use the theme props on the resulting component. Instead, I need to use `styled.divBox`. This of course is an easy fix, but it's not intuitive. 

## Example

```js
import styled from '@xstyled/styled-components'

const Wrapper = styled.div`
  // some css..
`

// Usage

<Wrapper mt={5}>
  // some children..
</Wrapper>
```

## Pitch

This would mean the overall API was simpler and simply "enhanced" styled components without the need for additional exports.

## But...

Perhaps separating these was intentional? If so, any reason why?

I'd be happy to put a PR together if this gets the go ahead. (I already have the typescript typings figured out for this too)

**Comment by gregberge** [comment]
Hello, for performance issues it is preferable to keep it like it is. A `styled.xxxBox` component is not as performant as a `styled.xxx` component. Also the migration from "styled-components" to "xstyled" would be a breaking change. That's the reasons why it will not happen, sorry!

**Comment by good-idea** [comment]
Sounds good! I thought it might be a performance thing. Thanks!
