### ISSUE TITLE
Svg attributes can't get values from theme

### ISSUE THREAD

**Issue by Calvein** [smooth-code/xstyled#118]
## 🐛 Bug Report

Svg colors attributes with values like `fill` & `stroke` can't take values from theme.

## To Reproduce

I made a small codesandbox with a `<div>` next to a `<rect>` and the `<rect>`'s fill stays black & its stroke stays transparent.
https://codesandbox.io/s/xstyled-svg-prop-not-working-n9lwd

## Expected behavior

Svg attributes like `fill`, `stroke` & `rx/ry` should pick values from the theme, I'm sure that I'm missing some be missing some

**Comment by xeladejo** [comment]
Excuse me if this a little off topic, but is it possible use `@xstyled/system` with icons loaded using `@svgr/webpack`?

**Comment by gregberge** [comment]
> Excuse me if this a little off topic, but is it possible use `@xstyled/system` with icons loaded using `@svgr/webpack`?

A little off topic yes, Yes it is possible but you have to wrap it into a `styled` component. You can do it using a custom template or just by creating a component by yourself for icons you want to use xstyled on.
