### ISSUE TITLE
Responsive styles not working as expected

### ISSUE THREAD

**Issue by Avizura** [smooth-code/xstyled#119]
## 🐛 Bug Report

When passing multiple responsive style props the order of resulting media queries is wrong.
![image](https://user-images.githubusercontent.com/11854101/87214726-e6bd3a80-c337-11ea-9f31-5a3547077d19.png)

## Expected behavior

I expect that in mobile first approach (which is used according to docs) media query with greater breakpoint will appear last and thus have a higher priority.

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/brave-bash-8v74n?file=/src/App.js
I'm passing the same padding-top and padding-bottom for `lg` breakpoint but it results in different paddings at large screen.

**Comment by EmilioAiolfi** [comment]
This seems to happen when we use a prop with only an `lg` breakpoint for example `height={{lg: '20x'}}` and combining it with other props with `md` and `lg` breakpoints: `height={{ xs: '10px', md: '20px', xl: 30px' }}`. 
This stops happening when removing the only `lg` prop or adding a `md` breakpoint to that property.

**Comment by EmilioAiolfi** [comment]
@gregberge I'm trying to find where this bug is. I thought it could be the function of `compose`. However I did tests, and the order of the breakpoints is correct on the return. Would you have any idea what it could be?
