### ISSUE TITLE
Any future plans on adding types?

### ISSUE THREAD

**Issue by ryee-dev** [smooth-code/xstyled#12]
Hey! I've been a long-time user of styled-components and thought I'd give xstyled a try since I could totally relate and understand the motivation behind it!

But regarding the topic of this issue, would it be possible to import styled-components/styled-system's preexisting type library? And if not, are there future plans to add types?

Anyways, I really appreciate your work on this library!

**Comment by neoziro** [comment]
Hello @ryee-dev, to be clear, I am not a TypeScript user so I can't maintain types. Adding types in the core of the library is too risky if core maintainers are not TypeScript friendly. That said, types of xstyled will have to be in https://github.com/DefinitelyTyped/DefinitelyTyped. At least at start.

**Comment by JaffParker** [comment]
Has anyone tried whether it's compatible with `@typed/styled-components`? Something tells me it should be, but I don't have time to try right now...

**Comment by neoziro** [comment]
Yes it should be compatible with `@types/styled-components` you will only miss `Box` and `styled.xxxBox`. If you can extends `@types/styled-components`, this is the good solution.

**Comment by timolins** [comment]
I wrote this `xstyled.d.ts` file for one of my projects, which applies all styled-components types to xstyled. Worked fine for me until this point.

The only thing is that `Box` types are missing, just like @neoziro mentioned.

```ts
declare module '@xstyled/styled-components' {
	import styled from 'styled-components'
	export * from 'styled-components'
	export default styled
}
```

(Related #2, #31)

**Comment by good-idea** [comment]
Hi all, I think I've about cracked the `Box` egg here. This is working well for me so far:

`xstyled.d.ts`

```ts
declare module '@xstyled/styled-components' {
  import styled, { StyledComponent, DefaultTheme } from 'styled-components'
  export * from 'styled-components'

  interface Breakpoints {
    xs: any
    sm: any
    md: any
    lg: any
    xl: any
  }

  type BreakpointObject<ArgType> = {
    [Key in keyof Breakpoints]?: ArgType
  }

  type WithBreakpointArgs<Props> = {
    [Key in keyof Props]?: Props[Key] | BreakpointObject<Props[Key]>
  }

  type FlexArgs =
    | 'flex-start'
    | 'center'
    | 'flex-end'
    | 'space-around'
    | 'space-between'

  interface BoxPropsBase {
    /* Display */
    display:
      | 'block'
      | 'inline-block'
      | 'inline'
      | 'flex'
      | 'grid'
      | 'none'
      | 'inherit'
      | 'initial'
    /* Color */
    color: string
    backgroundColor: string
    /* Margins */
    margin: number
    m: number
    marginTop: number
    mt: number
    marginRight: number
    mr: number
    marginBottom: number
    mb: number
    marginLeft: number
    ml: number
    mx: number
    my: number
    /* Padding */
    padding: number
    p: number
    paddingTop: number
    pt: number
    paddingRight: number
    pr: number
    paddingBottom: number
    pb: number
    paddingLeft: number
    pl: number
    px: number
    py: number
    /* Space & Layout */
    space: number
    width: number | string
    /* Grid */
    row: boolean
    col: boolean | number
    /* Flex */
    justifyContent: FlexArgs
    alignItems: FlexArgs
  }

  /* adds support for { xs: arg } and makes all props optional */
  export type BoxProps = WithBreakpointArgs<BoxPropsBase>

  export const Box: StyledComponent<
    'div',
    DefaultTheme,
    WithBreakpointArgs<BoxProps>
  >
  export default styled
}
```

This supports using the `<Box>` component with all of these props as the declared type (i.e. `width: number`), as well as with the media query syntax. So, these will all work

```ts
<Box margin={2}>:)</Box>
<Box margin={{ xs: 1, xl: 3 }}>:)</Box>
```

You can also create your own `styled(Box)` and the props will still work:

```ts
const Wrapper = styled(Box)`
  // ...
`

<Wrapper mt={2} />
```

To Do:

- [ ] Other props that can be passed on to `<Box>`, such as borders, are missing.
  - @neoziro is there a complete list of props that Box will accept?
- [ ] `xxBox` components are not supported. These can all be added manually, like:
   ```ts
   export const aBox: StyledComponent<
       'a',
       DefaultTheme,
       WithBreakpointArgs<BoxProps>
    >
   ```
    But I don't have the time (or need) for this. It might also be possible to iterate over all available tag names, but I'm not sure if you can create concatenated object names like this, for instance, `a` -> `aBox: StyledComponent<...>`
- [ ] It would be nice to automatically read what a user sets their `breakpoint` keys to in their own `styled.d.ts`, and use that for the Breakpoint keys, falling back to the styled-system defaults. In my project, i'll just be using `mobile`, `tablet`, `desktop`.

Anyone out there want to goof around with this and report back if things are working or not?

@neoziro , OK if we use this issue to track this stuff until it's to a point where we can add it to the DefinitelyTyped repository?

**Comment by neoziro** [comment]
> @neoziro is there a complete list of props that Box will accept?

Yes programatically you have access to the system props, or just https://www.smooth-code.com/open-source/smooth-ui/docs/box/#box-2

> @neoziro , OK if we use this issue to track this stuff until it's to a point where we can add it to the DefinitelyTyped repository?

Yes of course, feel free to use it to track the work!

**Comment by good-idea** [comment]
Hi all, I've added updated definitions in this gist:

https://gist.github.com/good-idea/96576e16c650c3730c53844d266d7149

Feel free to try them in your project, and add any comments/bugs in a comment in the gist. When it's been tested a little bit, I'll submit it to DefinitelyTyped.

**Comment by neoziro** [comment]
I am not a TypeScript user, it looks good but I can't review it. I don't add it to the repository because it wouldn't be maintained.

**Comment by good-idea** [comment]
@neoziro yup, no problem! I'm going to use them in my projects for a bit - maybe gather some feedback from any others who might be using them - and when they're ready to go I'll publish them in a separate package.

**Comment by stevejay** [comment]
@good-idea I've got a very rough draft of typings for `xstyled/system` in a [gist](https://gist.github.com/stevejay/6893d8454c291f319873d473b3d9e8f7).

**Comment by good-idea** [comment]
@stevejay these look great. I'm not familiar enough with `xstyled/system` and how it overlaps with this package - is there anything I can do to tweak mine to better fit? (I also didn't know about `ccstype`, i'll make a note to update my defs to use that)

**Comment by stevejay** [comment]
@good-idea There's a description comparing the two packages [here](https://www.smooth-code.com/open-source/xstyled/docs/getting-started/#introduction). Basically `xstyled/system` is the engine and `xstyled/system` is a wrapper for `styled-components` that integrates that engine.  AFAIK there's no tweaking necessary for your typings because there's no overlap between the two packages.

**Comment by stevejay** [comment]
@good-idea FYI I got the `xstyled/system` typings added to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/xstyled__system).

**Comment by good-idea** [comment]
Cool! I'll tidy up my types and submit those as well.

**Comment by wa4-fearless-otter** [comment]
@good-idea Is there any progress on this?

**Comment by good-idea** [comment]
@wa4-fearless-otter sorry, i never got around to this --- i might not be able to for a little while. In the meantime, the gist i linked to above covers most cases

**Comment by RoryOfByrne** [comment]
I had a go at some types for `@xstyled/emotion`: [link](https://gist.github.com/RoryOfByrne/597175865bae043d82f42a888fd7661a)

I basically took @good-idea's approach and replaced the `StyledComponent` generic type signature with the `emotion` signature: `StyledComponent<InnerProps, StyleProps, Theme>`.

The `xxBox` types are mapped directly from the original, so they may not all actually exist in the lib (?). I'm relatively new to xStyled/TS in general and I haven't used these types much yet, so please add a comment to the gist if there's anything I can improve.

Note: I added optional typing for your custom theme, near the top of the gist
