### ISSUE TITLE
Usage with Nextjs

### ISSUE THREAD

**Issue by GabrielDeM** [smooth-code/xstyled#138]
How should I setup Nextjs to work with xstyled ?

I tried a lot of things but I keep on having the famous:
`
Warning: Prop className did not match. Server: "sc-cCwQvm kpdCzu sc-czEUsQ jOIaqK" Client: "sc-dSnYFs ukjpK sc-cGKHXZ fvrtsY"
`

I manage to make it work if I only use `styled-components` by following this `Nextjs` exemple: https://github.com/vercel/next.js/tree/canary/examples/with-styled-components

But as soon as I use xstyled, things go wrong.

`_app.js`
```
import { ThemeProvider } from '@xstyled/styled-components';

import theme from '../assets/theme';

export default function App({ Component, pageProps }) {
	return (
		<ThemeProvider theme={theme}>
			<main>
				<Component {...pageProps} />
			</main>
		</ThemeProvider>
	);
}

```

`_document.js`
```
import Document from 'next/document';
import { ServerStyleSheet } from '@xstyled/styled-components';

export default class MyDocument extends Document {
	static async getInitialProps(ctx) {
		const sheet = new ServerStyleSheet();
		const originalRenderPage = ctx.renderPage;

		try {
			ctx.renderPage = () =>
				originalRenderPage({
					enhanceApp: (App) => (props) =>
						sheet.collectStyles(<App {...props} />),
				});

			const initialProps = await Document.getInitialProps(ctx);
			return {
				...initialProps,
				styles: (
					<>
						{initialProps.styles}
						{sheet.getStyleElement()}
					</>
				),
			};
		} finally {
			sheet.seal();
		}
	}
}

```

`.babelrc`

```
{
  "presets": ["next/babel"],
  "plugins": [["babel-plugin-styled-components", { "ssr": true }]]
}
```

**Comment by GabrielDeM** [comment]
I found why it wasn't working: `babel-plugin-styled-components` doesn't work with xstyled.

Check out this plugin: https://github.com/hookydev/babel-plugin-styled-components



```
npm install --save-dev @hookydev/babel-plugin-styled-components
```

`.babelrc`
```
{
  "presets": ["next/babel"],
  "plugins": [["@hookydev/babel-plugin-styled-components", { "ssr": true }]]
}
```

No more errors !

**Comment by mfbx9da4** [comment]
OMG banging my head against styled-components + nextjs issues for a while 

# 🤦‍♂️

**Comment by jbmusso** [comment]
Cross referencing https://github.com/gregberge/xstyled/issues/94 which provides an appropriate solution for this issue.
