### ISSUE TITLE
th utility returns a function and not a value

### ISSUE THREAD

**Issue by yairEO** [smooth-code/xstyled#151]
(version `1.19.1`)

Hi, I'm trying to create automatic CSS variables out of JSX, with a defined theme file:

```js
import React from 'react'
import styled, { getColor } from '@xstyled/styled-components'
import { getCSSVars } from 'utils' // <-- receives props and convert to CSS variables

const COLORS = {
  blue: getColor('blue') // <- returns a function and not a value
}

const StyledTag = styled(StyledTagBase)`
  ${getCSSVars('color')}
`

// using icons from:
// https://svgbox.net/
const Tag = ({ children, color = COLORS.blue }) => (
	<StyledTag color={COLORS[color]} onClick={onClick}>
      {children}
    </StyledTag>
)
 
export default Tag
```

I have a problem that using `th` or `getColor` shorthand, returns a function, rather than a value:

    blue: getColor('blue')

What should be done? Can a value be forced out of it?

Thanks for your kind help!

**Comment by SpicyPete** [comment]
I'm learning this library now, and am having success with this pattern

```
const StyledThing = styled(BaseComponent)`
 border: 2px solid ${p => th.color('primary')(p)};
```

**Comment by yairEO** [comment]
This is very different thing. I using the `th` method outside of `styled`, independently, outside of any React component, and it works differently in this case, returning a functiong.

**Comment by gregberge** [comment]
`th` is design to be used in `styled`.

```js
const StyledThing = styled(BaseComponent)`
 border: 2px solid ${th.color('primary')};
```

There is no simple way to use it outside. One method:

```js
const theme = useTheme()
const red = th.color('red')({ theme })
```

**Comment by yairEO** [comment]
@gregberge - the `useTheme` cannot be used outside of a React function, and I want to get a theme value outside the scope of React. Thanks for the response nonetheless.

**Comment by gregberge** [comment]
@yairEO it is not possible since theme is only available threw React Context, the only solution is to expose your theme as a constant.

**Comment by probablyup** [comment]
> `th` is design to be used in `styled`.
> 
> ```js
> const StyledThing = styled(BaseComponent)`
>  border: 2px solid ${th.color('primary')};
> ```
> 
> There is no simple way to use it outside. One method:
> 
> ```js
> const theme = useTheme()
> const red = th.color('red')({ theme })
> ```

In the documentation you actually use `th.color` in the creation of the theme. So does that pattern not actually work? https://xstyled.dev/docs/theme/#referencing-other-values

**Comment by agriffis** [comment]
@probablyup It works. https://codesandbox.io/s/xstyled-th-in-theme-p8hzz

When xstyled encounters a function as a replacement value, it calls it with props including the theme.

**Comment by probablyup** [comment]
Very strange... I cannot get that pattern to work for the life of me in my local project. Is it possible that the babel plugin `styled` replacement is messing with it? @gregberge

**Comment by agriffis** [comment]
TBH it's a pattern I prefer to avoid for sanity though, especially because `th` doesn't warn if the path doesn't exist:

https://github.com/gregberge/xstyled/blob/main/packages/system/src/th.ts#L62-L67

In my own projects I tend to: (1) build up the theme in chunks, e.g. base colors then derived/referenced. (2) Use a replacement `th` that warns if the path doesn't exist, and there's no default value. (Something we should probably consider for xstyled proper.)

**Comment by agriffis** [comment]
@probablyup FWIW I updated the sandbox above to use the babel macro and also a `styled.div`. I know that "it works for me" isn't the most encouraging response, but I hope it helps to narrow down the problem.

**Comment by eranimo** [comment]
The problem is, using `useColor` in a theme breaks the useTheme hook. I would expect the theme to return the aliased color token, but it returns a function instead. This makes it rather useless. Still a problem in 2025.
