### ISSUE TITLE
v2 Request: Match Styled-System Nomenclature

### ISSUE THREAD

**Issue by eugeneross** [smooth-code/xstyled#153]
## 🚀 Feature Proposal

It's frustrating using a similar API to `styled-system` but having to import the names of utilities in a different way. 

## Motivation

I find myself countless times importing a utility from `@xstyled/system` wondering why something isn't working or throwing an error, referring to `@xstyled/system` docs, then eventually `@xstyled/system` source code to figure out what's the correct utility name to import.

Not to mention, there is no `import` line of code in the docs for sake of example for the different utility APIs.

## Example

I want to import something like:
`import { flexbox } from '@xstyled/system'` just like I would for `import { flexbox } from 'styled-system'`

But I'm having to refer to the source code to learn that I have to import flexbox utilities like so:
`import { flexboxes } from '@xstyled/system'`

## Pitch

Just match the nomenclature so I don't have to have the burden of learning and mapping in my brain 😄

**Comment by gregberge** [comment]
@eugeneross v2 of xstyled will be way more complete than styled-system, I don't want to match its API sorry.

**Comment by eugeneross** [comment]
@gregberge fair enough!
