### ISSUE TITLE
Module not found with CRA/TypeScript

### ISSUE THREAD

**Issue by glecetre** [smooth-code/xstyled#2]
Hi :)

I cannot use this library with a basic TypeScript CRA.

## Steps

1. Create a new TS React app with `npx create-react-app my-app --typescript`
1. Add dependency `npm i @xstyled/styled-components`
1. Create a simple component:
  ```tsx
  import styled from "@xstyled/styled-components"

  const Toggle = styled.div`
    border: 1 violet;
    width: 16;
    height: 16;
  `
  export default Toggle
```
4. Launch with `npm start`

## Result
Failed compilation:
```
Failed to compile.

./node_modules/@xstyled/styled-components/dist/xstyled.es.js
Module not found: Can't resolve 'styled-components' in '/home/jeahel/dev/devtracker/node_modules/@xstyled/styled-components/dist'
```

**Comment by neoziro** [comment]
Hello @glecetre, styled-components is a peer dependency of the project. I should have mentioned it in the docs!

**Comment by glecetre** [comment]
Alright :-)
I'll try that tonight. In the meantime and while you mention the docs, there is something I'm not sure I understand. You mention the package `@xstyled/system` but in the installation process you don't instruct to install it, so what does it do and is it really necessary? Maybe the documentation could be a little bit clearer about the necessity of it.

**Comment by neoziro** [comment]
The package is a dependency of @xstyled/styled-components but if you use it directly it is better to install it.
