### ISSUE TITLE
Error with importing __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS

### ISSUE THREAD

**Issue by dapetrov** [smooth-code/xstyled#37]
## 🐛 Bug Report

I have that error with importing module "__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS" from styled-components

## To Reproduce

During building in Next.js when i run "yarn dev"

## Expected behavior

Normal dev run in Next.js

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/ssbed

## Run `npx envinfo --system --binaries --npmPackages @xstyled/system,@xstyled/styled-components,styled-components --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
 - Memory: 5.59 GB / 62.70 GB
 - Container: Yes
 - Shell: 4.4.12 - /bin/bash
## Binaries:
 - Node: 10.16.0 - /usr/local/bin/node
 - Yarn: 1.16.0 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
## npmPackages:
 - @xstyled/styled-components: 1.7.0 => 1.7.0
 - @xstyled/system: 1.7.0 => 1.7.0
 - styled-components: 5.0.0-beta.6-ej4 => 5.0.0-beta.6-ej4
```

**Comment by neoziro** [comment]
Hello, you use `styled-components` v5, it is not yet supported. It will be as soon as it will be officially released.

**Comment by dapetrov** [comment]
Ok, but it working pretty well before next.js update to 9.0.0. In 8.1 I have only warning about importing "__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS" module. Seems that in v5 there no more exporting it from styled.

Simply remove that import from https://github.com/smooth-code/xstyled/blob/master/packages/styled-components/src/index.js do the trick

```js
export {
  isStyledComponent,
  keyframes,
  ServerStyleSheet,
  StyleSheetConsumer,
  StyleSheetContext,
  StyleSheetManager,
  ThemeConsumer,
  ThemeContext,
  ThemeProvider,
  withTheme,
  __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS,
} from 'styled-components'

```

**Comment by neoziro** [comment]
OK thanks! I am interested to know if everything work with styled-components v5. They made a lot of changes and I wasn’t sure to be compatible. I will remove the export, it should not be used.

**Comment by dapetrov** [comment]
Yeah, everything works smooth👍, we are using your library in combination with v5, they reduced the tree tremendously, it's really a pleasure 😀
