### ISSUE TITLE
Can't get it to work in create react app in Codesandbox

### ISSUE THREAD

**Issue by wcastand** [smooth-code/xstyled#4]
## 🐛 Bug Report

I can't get it to work in code sandbox:
[code](https://codesandbox.io/embed/magical-noether-pshe2)

## Expected behavior

It should not output a type error.

## Link to repl or repo (highly encouraged)

[code](https://codesandbox.io/embed/magical-noether-pshe2)

## Error i get

```bash
TypeError
Cannot set property css of #<Object> which has only a getter
```

**Comment by AlxGolubev** [comment]
It works locally without any issues

**Comment by neoziro** [comment]
@wcastand I am working on it!

**Comment by neoziro** [comment]
https://codesandbox.io/s/delicate-sea-26fgw

**Comment by wcastand** [comment]
Awesome, i'll play with it tonight :)
Quick question, right now any variable is accepted. If i do `background-color: yellow;` it works.
You think it would be possible to have a `strict` mode where we only accept value from the system, to enforce the "theme" and design system?

**Comment by neoziro** [comment]
I don't want to ensure that, flexibility is the key! See #6 for discussion.

**Comment by wcastand** [comment]
That's why i'm not saying it should be the default but a possibility.
For me a design system is something to ensure that all your app is coherent. You can't really make sure of that if you can put any value anytime.

If i can't force a design system to specific value then i don't really see any value to a design system. I know it's my point of view and it's really "extreme".

Anyway, that project looks very cool.

**Comment by CompuIves** [comment]
Interesting, thanks for fixing it @neoziro! I'll look into what caused the error in CodeSandbox.
