### ISSUE TITLE
Compatibility with Styled-Components v3

### ISSUE THREAD

**Issue by paillenapple** [smooth-code/xstyled#43]
Hi,

I'm trying to make _xstyled_ work within a Styled-Components-v3.4.0-based app, but it seems it needs some v4 stuff to work properly : 

> export 'createGlobalStyle' (imported as 'createGlobalStyle$1') was not found in 'styled-components'

Should I migrate to v4 for best results ?

**Comment by neoziro** [comment]
Yes it is only compatible with styled-components v4.
