### ISSUE TITLE
Values passed to transform functions aren't resolved from the theme first

### ISSUE THREAD

**Issue by mattietea** [smooth-code/xstyled#48]
## 🐛 Bug Report

When using a [transformer](https://www.smooth-code.com/open-source/xstyled/docs/transformers/#use-custom-transformers), if the value comes from the theme, it isn't resolved. 

## To Reproduce

```js
theme.colors.primary = "#1975f8"

styled.div`
    background-color: green.light (this works)
    background-color: primary.light (this doesn't)
`
```
## Expected behavior

The theme color is resolved before getting to the transformer. 
Could be an issue with the regex used to get the css value? Maybe it tries to find `primary.light` in the theme?

## Link to repl or repo (highly encouraged)

https://codesandbox.io/embed/vigilant-edison-ofh4t?fontsize=14

Issues without a reproduction link are likely to stall.

```bash
## System:
 - OS: macOS 10.14.5
 - CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
 - Memory: 670.15 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 12.6.0 - /usr/local/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.10.3 - ~/Desktop/ui-trial/node_modules/.bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - @xstyled/styled-components: ^1.8.4 => 1.8.4 
 - @xstyled/system: ^1.8.4 => 1.8.4 
 - styled-components: ^4.3.2 => 4.3.2 
```

**Comment by gwitteveen** [comment]
While it would be nice if the transform function is called with the value resolved from the theme, I guess the way it works now is expected. But it's not hard to make it work the way you describe above. Just pass it the theme or use the alternative approach described in the comments.

```javascript
const theme = {
  transformers: {
    // In case you define your transformers outside your theme:
    // ===================================================
    // The transformer function is called with 2 arguments,
    // the second argument is an object with variants
    // and in this case your color tokens.
    color: (value, { variants }) => {
      const matches = value.match(/(.*)\.light/);
      if (!matches) return value;
      // this also works ⬇️
      // return lighten(0.2, variants[matches[1]] || matches[1]);
      return lighten(0.2, theme.colors[matches[1]] || matches[1]);
    }
  },
  colors: {
    primary: "#1975f8",
  }
};
```

That being said, [the documentation](https://www.smooth-code.com/open-source/xstyled/docs/transformers/) can set things off on the wrong foot as the example only works with [css colors](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value).

**Comment by neoziro** [comment]
Hello @mattietea, In fact you have access to the `rawValue`, if you look at [the call in the code](https://github.com/smooth-code/xstyled/blob/master/packages/system/src/style.js#L61) you have all infos. I think it should be good to document it. Could you submit a PR to mention it in the doc? 🙏
