### ISSUE TITLE
Replace confusing terms for breakpoints functions in documentation

### ISSUE THREAD

**Issue by jmlweb** [smooth-code/xstyled#51]
## 🚀 Feature Proposal

Replace confusing terms for breakpoints functions in documentation

## Motivation

Actually, description for `up` and `down` utils is switched

## Example

- up => Lets you apply style ~~up to~~ from a breakpoint (or down to a breakpoint)
- down => Lets you apply style ~~down to~~ up to a breakpoint

**Comment by neoziro** [comment]
You are right, I fixed it.
