### ISSUE TITLE
Get nested system styles using `styled`

### ISSUE THREAD

**Issue by stephenkoo** [smooth-code/xstyled#66]
## 💬 Questions and Help

I would really like to have a deeply nested theme object such as:
```
const theme = {
  colors: {
    primary: 'blue',
    text: '#000',
    background: '#fff',
    variants: {
      primary: {
        light: 'lightblue',
        dark: 'darkblue'
      }
    }
}

const StyledDiv = styled.div`
  border-color: primary;
  background-color: variants.primary.dark;
`
```

The theme is just simplified and could be flattened, but in my use case it would be a messy if the object is flattened, e.g. I want to have values like `colors.variants.state.error.dark`

It doesn't seem like there's a way to do this, is there?

**Comment by neoziro** [comment]
Your example should work great! This is exactly the way to do it :)
