### ISSUE TITLE
Link being passed style props

### ISSUE THREAD

**Issue by LoganArnett** [smooth-code/xstyled#67]
## 💬 Questions and Help
I am trying to figure out if I am doing something wrong when trying to create a styled version the `react-router-dom` Link component. I simply passed it into the `styled` method like `styled(Link)` to create an extensible Link but I am currently getting a few errors in the console like:
`React does not recognize the `backgroundColor` prop on a DOM element.` 

The `backgroundcolor` prop lives directly on the anchor tag and I am trying to figure out how to get around this.

**Comment by neoziro** [comment]
This is THE issue of loadable-components, the prop forwarding. To avoid that problem in xstyled, you have to use `createSystemComponent`:

```js
import { createSystemComponent, system } from '@xstyled/system'

const SystemLink = createSystemComponent(React, Link)

const StyledLink = styled(SysteLink)`
  ${system}
```

**Comment by LoganArnett** [comment]
Awesome thank you @neoziro
