### ISSUE TITLE
Variant props remaining on elements

### ISSUE THREAD

**Issue by LoganArnett** [smooth-code/xstyled#69]
## 🐛 Bug Report
I am trying to utilize variants for things like buttons and I am also trying to add a custom prop like `buttonType` in place of the default `variant`. I am still seeing them being passed directly to the html markup no matter how I construct the component. I have tried using the `createSystemComponent` method to avoid passing the props through but I still see the variant props passed directly to the html.

## To Reproduce

I put together a code sandbox that illustrates this but essentially any project utilizing variants should see the html with a `variant` attribute or with whatever you custom attribute was still on the element.

![image](https://user-images.githubusercontent.com/8780547/67241416-66f5e580-f421-11e9-8001-20cff3faffb8.png)

## Expected behavior
I would expect this prop to not be passed to the html element

## Link to repl or repo (highly encouraged)
https://codesandbox.io/embed/affectionate-khayyam-zv2xl

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages @xstyled/system,@xstyled/styled-components,styled-components --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 1.11 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 12.8.1 - ~/.nvm/versions/node/v12.8.1/bin/node
 - Yarn: 1.17.3 - ~/.nvm/versions/node/v12.8.1/bin/yarn
 - npm: 6.10.2 - ~/.nvm/versions/node/v12.8.1/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
```

**Comment by neoziro** [comment]
I am sorry but the issue is in styled-components, all props are forwarded to component by default. You have to create your own component and omitting props:

```js
function CustomButton({ variant, ...props }) {
   return <button {...props } />
}
```
