### ISSUE TITLE
{th} vs useTheme() usecases

### ISSUE THREAD

**Issue by yairEO** [smooth-code/xstyled#75]
Hi again, it's me, the person who is addicted to xStyled and asks many questions.

I see this [example here](https://www.smooth-code.com/open-source/xstyled/docs/styled-components-utilities/#usetheme):

```
function Example() {
  const theme = useTheme()
  return <div style={{ color: theme.colors.primary }}>Primary</div>
}
```

and this [example here](https://www.smooth-code.com/open-source/xstyled/docs/system-utilities/#theme-getters):

```
import { th } from '@xstyled/system'
const Container = styled.div`
  color: ${th('colors.primary')}; /* Read the primary color from the theme */
`
```

**My question is:** what use-cases does `useTheme()` that `th` doesn't?

Why is the theme in a hook? Themes cannot and should not change (while the app is running) so they don't have a state, so why is it in a hook-format?

You already have them, only different is that you also have to initialize the custom hook in order to use it, where on the other hand you can use `th` directly after importing, and both point to the exact same "theme" (as I understand it)

I also understand that one would want to use any of those only if the whole Application is not wrapper with a `ThemeProvider` that passes the `theme` prop to all components...

Thanks!

**Comment by neoziro** [comment]
Hello @yairEO, sometimes you could have to use a theme value outside the CSS. It is the purpose of `useTheme`. The example is probably a bad choice.

- `th('x')` is a shortcut for `props => props.theme.x`.
- `useTheme()` give you access to the theme in any component, not only in styled components
