### ISSUE TITLE
Overflow multi syntax not supported

### ISSUE THREAD

**Issue by LoganArnett** [smooth-code/xstyled#76]
## 💬 Questions and Help
This is a question in regards to the functionality around the `overflow` property. 

I have been using xstyled on a project that needs to support Chrome, Firefox, Edge, Safari, and their mobile equivalents. I recently had a very odd style regression when testing Safari and was able to debug it down to the fact the the `overflow` property was not being displayed correctly. I Chrome and Firefox were fine but in Edge and Safari it just disappeared. When I went digging for answers I found that the multiple `overflow: x y` syntax is [still not supported in all browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#Browser_compatibility). 

My question is should this project support the splitting of that property into `overflow-x` and `overflow-y` by default so that it supports all browsers?

**Comment by neoziro** [comment]
Hello @LoganArnett, no this is not the goal of this project polyfill or surcharge CSS. I think it should be related to styled-components itself. The next styled-components support stylis plugins so it could be done in it.
