### ISSUE TITLE
Allow manipulating theme colors (e.g. alpha)

### ISSUE THREAD

**Issue by stephenkoo** [smooth-code/xstyled#78]
## 🚀 Feature Proposal

I'd like to be able to modify colors (adjust alpha, hue, saturation) with the help of polished js:

```js
import styled from '@xstyled/styled-components'
import { th } from '@xstyled/system'
import { rgba } from 'polished'

const theme = {
  colors: {
    black: '#000'
  }
}

const Box = styled.div`
  color: ${rgba(th.colors('black'), 0.5)};
`
```

## Motivation

I have theme with several solid colors but must apply various alpha values for box shadows, shades, etc. Opacity is not useable because it would reduce the opacity of the text within the element as well as the background color.

## Pitch

Flexible color manipulation is crucial to allow users to continue using the colors specified in the sytem without having to create hardcode duplicate colors each time they want to create a variant color.

**Comment by stephyswe** [comment]
This!

**Comment by gregberge** [comment]
Already possible, in fact `th.xxx()` returns a function that takes prop. You can wrap this function and you get access to the value, the adapted example:

```js
import styled from '@xstyled/styled-components'
import { th } from '@xstyled/system'
import { rgba } from 'polished'

const theme = {
  colors: {
    black: '#000'
  }
}

const Box = styled.div`
  color: ${p => rgba(th.colors('black')(p), 0.5)};
`
```

**Comment by stephenkoo** [comment]
I've followed your example, but that still provides me with a CSS variable instead of the color value.

### Where I'm trying to access the hex/rgba value:
![image](https://user-images.githubusercontent.com/18624246/70967327-12ea4300-20ea-11ea-9135-fda2c33f6944.png)

### Dev console:
![image](https://user-images.githubusercontent.com/18624246/70967353-1f6e9b80-20ea-11ea-8ad5-749fe733bee3.png)

**Comment by gregberge** [comment]
Yeah if you are using CSS variables, you obviously can't do it. All colors have to be defined in the theme to be pre-processed before. You can't use it like that in CSS.

**Comment by stephenkoo** [comment]
My understanding is xstyled converting my colour values into into css
variables, since I'm not doing that anywhere in my code.

**Comment by stephenkoo** [comment]
Hi @gregberge, mind re-opening the issue? I'm pretty sure Xstyled is converting colors into CSS variables named `--xstyled-colors-` which prevents the solution from working. If it's not I'm not sure what library is renaming the colors before I can manipulate them.

Would a code demo help?

**Comment by gregberge** [comment]
@stephenkoo you have to turn off the transformation into CSS properties. https://xstyled.dev/docs/color-modes/#turn-off-custom-properties
