### ISSUE TITLE
CSS prop for Styled Components

### ISSUE THREAD

**Issue by ambertino** [smooth-code/xstyled#79]
What about CSS prop for Styled Components? There is Babel preset for the Emption but there is nothing I could find for the Styled Components to support it.

**Comment by gregberge** [comment]
Yeah it is not yet supported.

**Comment by gregberge** [comment]
CSS prop for styled-components has not a good support. It is backed by a Babel transforms, it means some edge cases are not good. Example : using a `state` property in the CSS.

I don't want to invest time on a feature that is not stable. If you want to use xstyled, you should not use CSS prop.

I added a word in the documentation to explain my choice.
