### ISSUE TITLE
Emotion v11

### ISSUE THREAD

**Issue by hennessyevan** [smooth-code/xstyled#84]
Will this project be updated to use emotion v11? They already have a fix in it for #77 see https://github.com/emotion-js/emotion/pull/1220 as well as improved typings for `Theme`

I'm working on a UI library that won't be out for a while so I'm working with v11 that should be out in less than a month, it would be nice to use xstyled alongside it but they've also renamed a lot of the packages so it won't work at the moment

**Comment by gregberge** [comment]
Yeah it is something planed!

**Comment by gregberge** [comment]
Looking at your example, the value is transformed by emotion `10` -> `10px`, you have to write your transformer in a way to strip unit.

**Comment by gregberge** [comment]
With the rename of packages it will be a breaking change. I am OK to bump a new major with emotion v11 support. Could you work on it?

**Comment by hennessyevan** [comment]
Yeah, would love to. I'm working on this library again soon so I'll open a PR for this when I get back to it

**Comment by ivanbanov** [comment]
Emotion 11 was just merged some hours ago :)
https://github.com/emotion-js/emotion/pull/1600

**Comment by camerontaylor** [comment]
FYI: This support should be straightforward. I've upgraded to emotion 11 and only needed these webpack aliases:

```
        resolve: {
            alias: {
                '@emotion/core': '@emotion/react',
                'emotion-theming': '@emotion/react',
```

The latest emotion also simplified all the hassle involved in getting the babel config playing nicely.
