### ISSUE TITLE
Custom Transformers in CSS?

### ISSUE THREAD

**Issue by hennessyevan** [smooth-code/xstyled#85]
## 🐛 Bug Report

Custom Transformers in theme are not respected when styling from the css prop

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/fervent-worker-q4y50

## Expected behavior

css prop should use transformers from the theme

**Comment by gregberge** [comment]
Looking at your example, the value is transformed by emotion 10 -> 10px, you have to write your transformer in a way to strip unit.
