### ISSUE TITLE
Styled Components V5

### ISSUE THREAD

**Issue by theo-mesnil** [smooth-code/xstyled#86]
## 🚀 Feature Proposal

Update `styled-components`  to V5 :)

## Motivation

https://github.com/styled-components/styled-components/releases/tag/v5.0.0

**Comment by gregberge** [comment]
Already full compatible, I will just update the peerDependencies.

**Comment by gregberge** [comment]
If you detect a bug, please open another issue!

**Comment by theo-mesnil** [comment]
Thanks ! :)
