### ISSUE TITLE
Support `fontStyle` in typography style props

### ISSUE THREAD

**Issue by P1X3L** [smooth-code/xstyled#91]
## 🚀 Feature Proposal

Add support for the `fontStyle` style prop.

## Motivation

I need this to close an issue in the design system I work on.

## Example

`<Box fontStyle="italic" />`

**Comment by gregberge** [comment]
You should use `style={{ fontStyle: '' }}` it has better performances if you don't need responsive.

Could you submit a PR to add it to supported properties? This file is the key: https://github.com/smooth-code/xstyled/blob/master/packages/system/src/styles/typography.js
