### ISSUE TITLE
How get theme value inside the component?

### ISSUE THREAD

**Issue by adambisek** [smooth-code/xstyled#93]
Hello there,
please, I have a specific case, where I need to get theme value inside component, like this: 

```javascript
const Component = (props) => {
   const primaryColor = th.color(”primary”, props)
...
```

But this doesnt work, because th helper is intended to be used inside styled-components.

I note that this component is under xstyled context provider.

How to do this?

**Comment by mintyfloss** [comment]
I've done this by using `useTheme`.

**Comment by gregberge** [comment]
Yeah `useTheme` is the correct way to do it, if you want `th`:

```js
const theme = useTheme()
const primary = th.color('primary')({ theme })
```
